// Kana
export const allKanaObject = {
  a: ["a", "i", "u", "e", "o"],
  ka: ["ka", "ki", "ku", "ke", "ko"],
  sa: ["sa", "shi", "su", "se", "so"],
  ta: ["ta", "chi", "tsu", "te", "to"],
  na: ["na", "ni", "nu", "ne", "no"],
  ha: ["ha", "hi", "fu", "he", "ho"],
  ma: ["ma", "mi", "mu", "me", "mo"],
  ya: ["ya", "yu", "yo"],
  ra: ["ra", "ri", "ru", "re", "ro"],
  wa: ["wa", "wo", "n"],
  ga: ["ga", "gi", "gu", "ge", "go"],
  za: ["za", "ji", "zu", "ze", "zo"],
  da: ["da", "zi", "zu", "de", "do"],
  ba: ["ba", "bi", "bu", "be", "bo"],
  pa: ["pa", "pi", "pu", "pe", "po"],
  kya: ["kya", "kyu", "kyo"],
  gya: ["gya", "gyu", "gyo"],
  sha: ["sha", "shu", "sho"],
  ja: ["jya", "jyu", "jyo"],
  cha: ["cha", "chu", "cho"],
  dya: ["dya", "dyu", "dyo"],
  nya: ["nya", "nyu", "nyo"],
  hya: ["hya", "hyu", "hyo"],
  bya: ["bya", "byu", "byo"],
  pya: ["pya", "pyu", "pyo"],
  mya: ["mya", "myu", "myo"],
  rya: ["rya", "ryu", "ryo"],
};
